"""create insights and conversations

Revision ID: 32a18dec3954
Revises:
Create Date: 2026-09-17 11:14:08.538495

"""

import json
import re
import unicodedata
import uuid
from collections.abc import Sequence
from pathlib import Path

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

SEED_FILE = Path(__file__).resolve().parents[1] / "seed" / "insights_v1.json"
SEED_NAMESPACE = uuid.UUID("9a4b3c1e-6f0d-4c8e-9b7a-2d5e1f3a4c6b")
LANGUAGES = ("en", "es", "fr", "de")


def normalize(text: str) -> str:
    # Copied, not imported, so this migration never changes when app code does
    decomposed = unicodedata.normalize("NFKD", text.casefold())
    return "".join(char for char in decomposed if not unicodedata.combining(char))


def seed_rows() -> list[dict[str, object]]:
    seed = json.loads(SEED_FILE.read_text(encoding="utf-8"))
    rows = []
    for insight in seed["insights"]:
        words = seed["topics"][insight["category"]] + [
            part for tag in insight["tags"] for part in re.findall(r"\w+", tag)
        ]
        keywords = sorted({normalize(word) for word in words})
        for language in LANGUAGES:
            text = insight["translations"][language]
            rows.append(
                {
                    # Stable ids, so reseeding produces the same rows
                    "id": uuid.uuid5(SEED_NAMESPACE, f"{insight['key']}:{language}"),
                    "language": language,
                    "category": insight["category"],
                    "title": text["title"],
                    "content": text["content"],
                    "source": insight["source"],
                    "confidence": insight["confidence"],
                    "tags": insight["tags"],
                    "keywords": keywords,
                }
            )
    return rows


# revision identifiers, used by Alembic.
revision: str = "32a18dec3954"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_table(
        "insights",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=50)), nullable=False),
        sa.Column("keywords", postgresql.ARRAY(sa.String(length=50)), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insights")),
    )
    op.create_index(
        op.f("ix_insights_language"), "insights", ["language"], unique=False
    )
    op.create_table(
        "prompt_responses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("target_language", sa.String(length=5), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("insight_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_prompt_responses_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_responses")),
    )
    op.create_index(
        op.f("ix_prompt_responses_conversation_id"),
        "prompt_responses",
        ["conversation_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    insights = sa.table(
        "insights",
        sa.column("id", sa.Uuid()),
        sa.column("language", sa.String()),
        sa.column("category", sa.String()),
        sa.column("title", sa.String()),
        sa.column("content", sa.Text()),
        sa.column("source", sa.String()),
        sa.column("confidence", sa.Float()),
        sa.column("tags", postgresql.ARRAY(sa.String())),
        sa.column("keywords", postgresql.ARRAY(sa.String())),
    )
    op.bulk_insert(insights, seed_rows())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_prompt_responses_conversation_id"), table_name="prompt_responses"
    )
    op.drop_table("prompt_responses")
    op.drop_index(op.f("ix_insights_language"), table_name="insights")
    op.drop_table("insights")
    op.drop_table("conversations")
    # ### end Alembic commands ###
